package com.owenjg.regexsynthesiser.controller;

import com.owenjg.regexsynthesiser.validation.Examples;
import com.owenjg.regexsynthesiser.validation.RegexComparator;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.stage.FileChooser;
import javafx.stage.Stage;
import java.awt.Toolkit;

import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;

/**
 * Controller for the regex display view that shows the generated regular expressions
 * and provides options to copy, export, or return to the previous screen.
 *
 * This controller displays both the pattern analyser and DFA-based regex results,
 * along with comparison metrics and utility functions for the user.
 */
public class DisplayRegexController {

    @FXML private Label analyserRegexLabel; // Label to display the pattern analyser regex
    @FXML private Label dfaRegexLabel;      // Label to display the DFA-based regex
    @FXML private Label titleText;         // Label for the title
    @FXML private Label elapsedTimeText;   // Label for the elapsed time
    @FXML private Label statusText;        // Label for status updates
    @FXML private Label ratioLabel;        // Label for displaying the ratios

    private Stage stage;

    private String elapsedTime;
    private String analyserRegex;
    private String dfaRegex;
    private Examples currentExamples;

    /**
     * Sets the main application stage for this controller.
     *
     * @param stage The primary stage for this JavaFX application
     */
    public void setStage(Stage stage) {
        this.stage = stage;
        stage.setTitle("Generated Regular Expressions");
    }

    /**
     * Sets the values to display in the view.
     *
     * @param elapsedTime Time taken for generation in seconds
     * @param generatedRegex The generated regex string(s)
     * @param ce The Examples object containing positive and negative examples
     */
    public void setValues(String elapsedTime, String generatedRegex, Examples ce) {
        currentExamples = ce;
        elapsedTimeText.setText("Time taken: " + elapsedTime + " seconds");

        // Check if the generatedRegex contains both regex patterns
        if (generatedRegex.contains("Pattern Analyser:") && generatedRegex.contains("DFA-based:")) {
            // Parse the combined string
            parseRegexResults(generatedRegex);
        } else {
            // Fallback to setting both labels to the same regex
            analyserRegexLabel.setText(generatedRegex);
            dfaRegexLabel.setText(generatedRegex);
            this.analyserRegex = generatedRegex;
            this.dfaRegex = generatedRegex;
        }

        this.elapsedTime = elapsedTime;

        // Calculate and display the ratios
        updateRatios(analyserRegex, dfaRegex);
    }

    /**
     * Calculates and displays the ratio metrics comparing the two regex patterns.
     *
     * @param analyserRegex The regex generated by the pattern analyser
     * @param dfaRegex The regex generated from the DFA
     */
    private void updateRatios(String analyserRegex, String dfaRegex) {
        if (analyserRegex == null || dfaRegex == null ||
                analyserRegex.equals("Not available") || dfaRegex.equals("Not available")) {
            statusText.setText("Ratio metrics not available");
            return;
        }

        // Calculate the ratios
        double lengthRatio = RegexComparator.getLengthRatio(analyserRegex, dfaRegex);
        double complexityRatio = RegexComparator.getComplexityRatio(analyserRegex, dfaRegex);

        // Format the ratios
        String formattedLengthRatio = String.format("%.2f:1", lengthRatio);
        String formattedComplexityRatio = String.format("%.2f:1", complexityRatio);

        // Create a concise metrics message for the status area
        String ratioMetrics = "Length ratio (PA:DFA): " + formattedLengthRatio +
                "\nComplexity ratio (PA:DFA): " + formattedComplexityRatio;

        // Update the status text
        ratioLabel.setText(ratioMetrics);
    }

    /**
     * Handles the click event for the Export button.
     * Exports the examples and regex results to a text file.
     *
     * @throws IOException If there is an error writing to the file
     */
    @FXML
    protected void onExportButtonClick() throws IOException {
        FileChooser fc = new FileChooser();
        fc.setTitle("Save positive and negative examples");

        fc.getExtensionFilters().addAll(
                new FileChooser.ExtensionFilter("Text Files", "*.txt")
        );

        try {
            File selectedFile = fc.showSaveDialog(stage);

            if (selectedFile != null) {
                try (FileWriter fw = new FileWriter(selectedFile)) {
                    writeToFile(fw);
                } catch (IOException e) {
                    updateStatusLabel("ERROR: Exporting the file");
                    e.printStackTrace();
                }
                updateStatusLabel("Successfully exported the file: " + selectedFile.getName());
            }
        } catch (Exception e) {
            updateStatusLabel("ERROR: Unexpected error during export");
            e.printStackTrace();
        }
    }

    /**
     * Writes the examples and regex results to the specified file.
     *
     * @param fw The FileWriter for the output file
     * @throws IOException If there is an error writing to the file
     */
    private void writeToFile(FileWriter fw) throws IOException {
        List<String> positives = currentExamples.getPositiveExamples();
        List<String> negatives = currentExamples.getNegativeExamples();

        for (int i = 0; i < positives.size(); i++) {
            fw.write(positives.get(i));
            if (i < positives.size() - 1) {
                fw.write("|");
            }
        }

        fw.write("\n::\n");

        for (int i = 0; i < negatives.size(); i++) {
            fw.write(negatives.get(i));
            if (i < negatives.size() - 1) {
                fw.write("|");
            }
        }

        fw.write("\n::\n");
        fw.write("Pattern Analyser Regex: " + analyserRegex);
        fw.write("\nDFA-based Regex: " + dfaRegex);
        fw.write("\n\n" + ratioLabel.getText());
        fw.close();
    }

    /**
     * Handles the click event for the Copy Analyser button.
     * Copies the pattern analyser regex to the clipboard.
     *
     * @throws IOException If there is an error during the copy operation
     */
    @FXML
    protected void onCopyAnalyserButtonClick() throws IOException {
        copyToClipboard(analyserRegex);
        updateStatusLabel("Copied the Pattern Analyser regex to clipboard!");
    }

    /**
     * Handles the click event for the Copy DFA button.
     * Copies the DFA-based regex to the clipboard.
     *
     * @throws IOException If there is an error during the copy operation
     */
    @FXML
    protected void onCopyDFAButtonClick() throws IOException {
        copyToClipboard(dfaRegex);
        updateStatusLabel("Copied the DFA-based regex to clipboard!");
    }

    /**
     * Handles the click event for the Copy Both button.
     * Copies both regexes to the clipboard with appropriate labels.
     *
     * @throws IOException If there is an error during the copy operation
     */
    @FXML
    protected void onCopyBothButtonClick() throws IOException {
        String combinedRegex = "Pattern Analyser: " + analyserRegex + "\nDFA-based: " + dfaRegex;
        copyToClipboard(combinedRegex);
        updateStatusLabel("Copied both regexes to clipboard!");
    }

    /**
     * Copies the specified text to the system clipboard.
     *
     * @param text The text to copy to the clipboard
     */
    private void copyToClipboard(String text) {
        StringSelection stringSelection = new StringSelection(text);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
    }

    /**
     * Handles the click event for the Back button.
     * Returns to the examples input view.
     *
     * @throws IOException If there is an error loading the previous view
     */
    @FXML
    protected void onBackButtonClick() throws IOException {
        // Load the previous input examples form
        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("/com/owenjg/regexsynthesiser/input-examples-view.fxml"));
        VBox previousRoot = fxmlLoader.load();

        // Get the controller for the previous form
        InputExamplesController previousController = fxmlLoader.getController();

        // Set the stage for the previous controller
        previousController.setStage(stage);

        // Create a new scene with the previous form
        Scene previousScene = new Scene(previousRoot, 800, 600);
        previousScene.getStylesheets().add(getClass().getResource("/com/owenjg/regexsynthesiser/styles.css").toExternalForm());

        stage.setScene(previousScene);
    }

    /**
     * Updates the status label with a message and applies appropriate styling.
     *
     * @param message The message to display in the status label
     */
    private void updateStatusLabel(String message) {
        // Clear previous styles
        statusText.getStyleClass().remove("error");

        // Check if message starts with "ERROR:" or contains specific error keywords
        if (message.toUpperCase().startsWith("ERROR:")) {
            statusText.getStyleClass().add("error");
        }

        // Set the message
        statusText.setText(message);
    }

    /**
     * Parses the combined regex results string into separate analyser and DFA components.
     *
     * @param combinedRegex The combined regex string containing both patterns
     */
    private void parseRegexResults(String combinedRegex) {
        // Initialise default values
        analyserRegex = "Not available";
        dfaRegex = "Not available";

        if (combinedRegex != null) {
            String[] parts = combinedRegex.split("\n");

            for (String part : parts) {
                if (part.startsWith("Pattern Analyser:")) {
                    analyserRegex = part.substring("Pattern Analyser:".length()).trim();
                } else if (part.startsWith("DFA-based:")) {
                    dfaRegex = part.substring("DFA-based:".length()).trim();
                }
            }
        }

        // Update UI
        analyserRegexLabel.setText(analyserRegex);
        dfaRegexLabel.setText(dfaRegex);

        // Update the status text with ratio metrics
        updateRatios(analyserRegex, dfaRegex);
    }
}